version: '3'

tasks:
  up:
    desc: Dockerの起動
    cmds:
      - docker compose up -d
  down:
    desc: Dockerの終了
    cmds:
      - docker compose down
  build:
    desc: Docker build
    cmds:
      - docker compose build